import { useState } from 'react';
import AppLayout from '@/layouts/app-layout';
import { Head } from '@inertiajs/react';
import { MessageList, ChatInput, EmptyState } from '@/components/chat';
import type { Message } from '@/types/chat';
import { dashboard } from '@/routes';
import type { BreadcrumbItem } from '@/types';

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: 'Dashboard',
        href: dashboard().url,
    },
    {
        title: 'Chat Demo',
        href: '/chat/demo',
    },
];

export default function ChatDemo() {
    const [messages, setMessages] = useState<Message[]>([]);
    const [isProcessing, setIsProcessing] = useState(false);
    const [remainingRequests, setRemainingRequests] = useState(20);

    const handleSendMessage = (content: string) => {
        // Add user message
        const userMessage: Message = {
            id: Date.now(),
            conversation_id: 1,
            role: 'user',
            content,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
        };

        setMessages((prev) => [...prev, userMessage]);
        setIsProcessing(true);
        setRemainingRequests((prev) => prev - 1);

        // Simulate AI response
        setTimeout(() => {
            const aiMessage: Message = {
                id: Date.now() + 1,
                conversation_id: 1,
                role: 'assistant',
                content: `This is a demo response to: "${content}".\n\nIn a real application, this would be generated by the AI service. The message would be fetched via polling after the backend processes the request.`,
                created_at: new Date().toISOString(),
                updated_at: new Date().toISOString(),
            };

            setMessages((prev) => [...prev, aiMessage]);
            setIsProcessing(false);
        }, 2000);
    };

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Chat Demo" />

            <div className="flex h-[calc(100vh-4rem)] flex-col overflow-hidden rounded-xl border border-sidebar-border/70 bg-background dark:border-sidebar-border">
                {/* Header */}
                <div className="border-b p-4">
                    <h2 className="text-lg font-semibold">Chat Demo</h2>
                    <p className="text-sm text-muted-foreground">
                        Testing chat components with mock data
                    </p>
                </div>

                {/* Messages */}
                {messages.length === 0 ? (
                    <EmptyState
                        title="Chat Component Demo"
                        description="Send a message below to see the components in action. This is using mock data for demonstration."
                        icon="sparkles"
                    />
                ) : (
                    <MessageList messages={messages} isProcessing={isProcessing} />
                )}

                {/* Input */}
                <ChatInput
                    onSend={handleSendMessage}
                    disabled={isProcessing}
                    remainingRequests={remainingRequests}
                    placeholder="Type a message to test the chat components..."
                />
            </div>
        </AppLayout>
    );
}
